### ISSUE TITLE
Produzir o Protótipo

### ISSUE THREAD

**Issue by leticiaarj** [fga-eps-mds/2021-2-Eu_Pescador-Doc#30]
Baseado nas novas funcionalidades.

**Comment by clara-ribeiro** [comment]
Desenvolvimento do [protótipo](https://www.figma.com/file/FFU62xKsptjJQNp58hNp3M/Eu-Pescador?node-id=0%3A1) das seguintes funcionalidades/páginas:

- Recuperação de senha na página de login;
- Nova página Mapa, com marcação da localização dos registros feitos;
- Modal de termos de uso.

**Comment by leticiaarj** [comment]
Protótipo revisado.
